"""Build analysis/report_microphone_scaling.md from whatever micgain runs have finished.

Safe to run mid-sweep: cells with no evaluation yet are marked pending rather than guessed. Reads
the same compare.json files the rest of the campaign uses, so no number here is re-derived.

  python3 analysis/micgain_report.py
"""
import os, sys, json, re, glob
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

MO = json.load(open("/root/storage/supple_mic_gain/mic_order.json"))
ORDER = MO["progressive_order"]


def _store():
    d = {}
    for f in ("comparison_0820/compare.json", "comparison_0820/mp3d_eval/compare.json",
              "comparison_0820/micgain_eval/compare.json"):
        if os.path.exists(f):
            try: d.update(json.load(open(f)))
            except Exception: pass
    return d


def _bestval(run):
    p = f"comparison_0820/logs/{run}.log"
    if not os.path.exists(p): return None
    v = [float(m.group(1)) for L in open(p) for m in [re.search(r"val_MAE=([\d.]+)m", L)] if m]
    return min(v) if v else None


def rows(prefix):
    st = _store()
    out = []
    for k in range(1, len(ORDER) + 1):
        ch = 2 * k
        run = f"{prefix}{ch}"
        hs = sorted(ORDER[:k])
        gaps = [(hs[(i + 1) % k] - hs[i]) % 360 for i in range(k)] if k > 1 else [360]
        out.append(dict(ch=ch, k=k, added=ORDER[k - 1], headings=hs, maxgap=max(gaps),
                        run=run, mae=st.get(run, {}).get("MAE"), val=_bestval(run),
                        done=os.path.exists(f"comparison_0820/logs/{run}.log")
                             and "[done]" in open(f"comparison_0820/logs/{run}.log").read()))
    return out


def fmt(v, n=4):
    return "pending" if v is None else f"{v:.{n}f}"


def main():
    ours = rows("0820_mg_ours_m")
    eco = rows("0820_mg_eco_m")
    L = ["# Microphone-scaling study — does the model use extra observations?", "",
         "Generated by `analysis/micgain_report.py`; cells with no test evaluation yet read",
         "`pending` rather than being filled in. Dataset: `/root/storage/supple_mic_gain`", ""]
    L += ["## Microphone geometry", "",
          f"{len(ORDER)} binaural headings on a {MO['grid_deg']}-degree yaw grid, so N_max = {2*len(ORDER)} channels.",
          "Headings are added in the dataset's own bisection order (each new yaw falls in the largest",
          "remaining gap), which makes the subsets nested: M2 subset M4 subset ... subset M%d." % (2*len(ORDER)),
          "k = 4 reproduces exactly the released r8 input {0, 90, 180, 270}.", "",
          "| ch | k | added yaw | headings | largest gap |", "|---:|---:|---:|---|---:|"]
    for r in ours:
        L.append(f"| {r['ch']} | {r['k']} | {r['added']} | {', '.join(str(h) for h in r['headings'])} | {r['maxgap']} deg |")
    L += ["", "## Results", "",
          "| # mics | headings | Ours MAE | Ours (best val) | EchoDiffusion MAE |",
          "|---:|---|---:|---:|---:|"]
    for a, b in zip(ours, eco):
        L.append(f"| {a['ch']} | {', '.join(str(h) for h in a['headings'])} | "
                 f"{fmt(a['mae'])} | {fmt(a['val'])} | {fmt(b['mae'])} |")
    # marginal gains, only where two consecutive cells are both measured
    L += ["", "## Marginal gain per +2 microphones", "", "| transition | Ours dMAE | EchoDiffusion dMAE |", "|---|---:|---:|"]
    for i in range(1, len(ours)):
        for nm, arr in (("o", ours), ("e", eco)):
            pass
        do = (ours[i]["mae"] - ours[i-1]["mae"]) if (ours[i]["mae"] and ours[i-1]["mae"]) else None
        de = (eco[i]["mae"] - eco[i-1]["mae"]) if (eco[i]["mae"] and eco[i-1]["mae"]) else None
        L.append(f"| {ours[i-1]['ch']} -> {ours[i]['ch']} | "
                 f"{'pending' if do is None else f'{do:+.4f}'} | {'pending' if de is None else f'{de:+.4f}'} |")
    done_o = sum(1 for r in ours if r["mae"] is not None)
    done_e = sum(1 for r in eco if r["mae"] is not None)
    L += ["", f"_status: Ours {done_o}/{len(ours)} cells evaluated, EchoDiffusion {done_e}/{len(eco)}._"]
    os.makedirs("analysis", exist_ok=True)
    open("analysis/report_microphone_scaling.md", "w").write("\n".join(L) + "\n")
    print("\n".join(L[:14]))
    print(f"\n[saved] analysis/report_microphone_scaling.md  (Ours {done_o}/{len(ours)}, Eco {done_e}/{len(eco)})")


if __name__ == "__main__":
    main()
